services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: task_flow_backend:lastest
    ports:
      - "8080:8080"
    env_file:
      - ./backend/product.env
    depends_on:
      - database
      - cache
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "5173:80"
  database:
    image: mysql:8.4-oracle
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
volumes:
  db_data: